"""UI 组件 — 各功能面板"""
from src.ui.widgets.video_recorder import VideoRecorderPanel
from src.ui.widgets.status_panel import StatusPanel
from src.ui.widgets.motor_control import MotorControlPanel
from src.ui.widgets.log_panel import LogPanel
from src.ui.widgets.camera_plugin import CameraPluginPanel
from src.ui.widgets.model_plugin import ModelPluginPanel
from src.ui.widgets.fringe_center_plugin import FringeCenterPluginPanel
from src.ui.widgets.agent_plugin import AgentPluginPanel
from src.ui.widgets.collapsible import CollapsibleFrame
from src.ui.widgets.plugin_toggles import PluginToggleBar
from src.ui.widgets.auto_center_control import AutoCenterControlPanel
from src.ui.widgets.micrometer_plugin import MicrometerPluginPanel
from src.ui.widgets.floating_assistant import FloatingAssistantWindow
from src.ui.widgets.temporary_measurement import TemporaryMeasurementPanel
